"""Shared filesystem-memory layer for the agent fleet.

Subclasses Anthropic's BetaAbstractMemoryTool (memory_20250818) for cloud
agents and exposes a read-only `inject_memories_into_prompt()` helper for
local-Ollama agents that don't speak the tool protocol.

Mount: vault/90_system/fleet-memory/ (resolved from config.toml).
Namespacing: {mount}/{agent_id}/ for per-agent state, {mount}/shared/ for
cross-agent lessons. Promotion to shared is via explicit promote_to_shared()
call — never an implicit tool command.

Path traversal is the load-bearing safety check: every read/write goes
through _resolve_path(), which performs realpath + prefix containment.
Any attempt to escape the mount via .., absolute paths, or symlinks raises
PathEscapeError.

See agents-sdk/docs/plans/2026-05-27-fleet-memory-phase-1-plan.md.
"""

from __future__ import annotations

import logging
import re
from datetime import date
from pathlib import Path

from lib.filelock import FileLock

logger = logging.getLogger("fleet_memory")


class PathEscapeError(ValueError):
    """A memory command tried to access a path outside the mount root."""


def _resolve_path(mount_root: Path, raw_path: str) -> Path:
    """Resolve `raw_path` against `mount_root`, rejecting any escape.

    Args:
        mount_root: The fleet-memory mount directory. Must already exist.
        raw_path: A relative path the caller wants to access inside the mount.
            An empty string is rejected.

    Returns:
        The fully-resolved absolute path, guaranteed to live under
        `mount_root.resolve()`. The path itself may not exist yet (the
        memory-tool `create` command needs to write new files); the guard
        only ensures *where it would land* is inside the mount.

    Raises:
        PathEscapeError: If `raw_path` is empty, if it resolves outside the
            mount (via `..`, absolute path, or symlink chain), or if any
            intermediate component is a symlink pointing outside the mount.
    """
    if not raw_path:
        raise PathEscapeError("empty path")

    mount_real = mount_root.resolve()
    if not mount_real.exists():
        raise PathEscapeError(f"mount root does not exist: {mount_real}")

    candidate = (mount_real / raw_path).resolve()

    # Containment check via Path semantics (handles cross-platform separators
    # correctly; string prefix would false-positive on /tmp/fleet vs /tmp/fleet2).
    try:
        candidate.relative_to(mount_real)
    except ValueError as exc:
        raise PathEscapeError(
            f"path escapes mount: candidate={candidate} mount={mount_real}"
        ) from exc

    return candidate


MANIFEST_HEADER = (
    "# Fleet Memory Index\n\n"
    "_Auto-generated by lib.fleet_memory. Do not edit by hand._\n\n"
    "One-line summary per memory file. Used by agents for the\n"
    "manifest-then-top-5 retrieval pattern (Perplexity DR, Apr 2026).\n\n"
)


def ensure_mount(mount_root: Path, *, agent_ids: list[str]) -> None:
    """Create the mount layout idempotently.

    Layout:
        {mount_root}/
            shared/
            {agent_id}/         (one per id passed in)
            MEMORY_INDEX.md     (created with header if absent)

    Existing files are never overwritten. Safe to call on every run.
    """
    mount_root.mkdir(parents=True, exist_ok=True)
    (mount_root / "shared").mkdir(exist_ok=True)
    for aid in agent_ids:
        (mount_root / aid).mkdir(exist_ok=True)
    manifest = mount_root / "MEMORY_INDEX.md"
    if not manifest.exists():
        manifest.write_text(MANIFEST_HEADER, encoding="utf-8")


from anthropic.lib.tools import BetaAbstractMemoryTool
from anthropic.types.beta import (
    BetaMemoryTool20250818CreateCommand,
    BetaMemoryTool20250818DeleteCommand,
    BetaMemoryTool20250818InsertCommand,
    BetaMemoryTool20250818RenameCommand,
    BetaMemoryTool20250818StrReplaceCommand,
    BetaMemoryTool20250818ViewCommand,
)


class NamespaceViolation(ValueError):
    """A tool tried to write outside its agent_id namespace AND outside shared/."""


class FleetMemoryTool(BetaAbstractMemoryTool):
    """Per-agent memory tool scoped to {mount_root}/{agent_id}/ for writes.

    Reads are allowed from anywhere under the mount (so agents can see
    shared/ and peer namespaces); writes are restricted to the agent's
    own namespace plus shared/. Use promote_to_shared() for an explicit,
    auditable promotion path.
    """

    def __init__(
        self,
        *,
        mount_root: Path,
        agent_id: str,
    ) -> None:
        super().__init__()
        if not agent_id:
            raise ValueError("agent_id is required")
        self._mount_root = mount_root
        self._agent_id = agent_id

    # ─── path discipline helpers ───────────────────────────────────────

    def _resolve(self, raw_path: str) -> Path:
        # Strip any leading "/memories/" prefix the Anthropic protocol uses.
        # Agents see paths as "/memories/vault_synthesizer/foo.md" but on
        # disk we mount at {mount_root}/vault_synthesizer/foo.md.
        relpath = raw_path.lstrip("/")
        if relpath.startswith("memories/"):
            relpath = relpath[len("memories/"):]
        return _resolve_path(self._mount_root, relpath)

    def _assert_write_allowed(self, target: Path) -> None:
        rel = target.relative_to(self._mount_root.resolve())
        first = rel.parts[0] if rel.parts else ""
        if first == self._agent_id or first == "shared":
            return
        raise NamespaceViolation(
            f"agent={self._agent_id} tried to write {rel} — only "
            f"{self._agent_id}/** and shared/** are writable"
        )

    # ─── internal command implementations (testable without SDK objects) ──

    def _view_path(self, raw_path: str) -> str:
        target = self._resolve(raw_path)
        if target.is_dir():
            entries = sorted(p.name for p in target.iterdir())
            return "\n".join(entries) if entries else "(empty)"
        return target.read_text(encoding="utf-8")

    def _create_path(self, raw_path: str, body: str) -> str:
        target = self._resolve(raw_path)
        self._assert_write_allowed(target)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        return f"created {target.relative_to(self._mount_root.resolve())}"

    # ─── internal command implementations (continued) ──────────────────

    def _str_replace_path(self, raw_path: str, old: str, new: str) -> str:
        target = self._resolve(raw_path)
        self._assert_write_allowed(target)
        body = target.read_text(encoding="utf-8")
        count = body.count(old)
        if count == 0:
            raise ValueError(f"old string not found in {raw_path}")
        if count > 1:
            raise ValueError(
                f"old string appears {count} times in {raw_path}; must be unique"
            )
        target.write_text(body.replace(old, new), encoding="utf-8")
        return f"str_replace ok in {raw_path}"

    def _insert_path(self, raw_path: str, insert_line: int, insert_text: str) -> str:
        target = self._resolve(raw_path)
        self._assert_write_allowed(target)
        body = target.read_text(encoding="utf-8")
        lines = body.splitlines(keepends=True)
        if insert_line < 0 or insert_line > len(lines):
            raise ValueError(
                f"insert_line {insert_line} out of range for {raw_path} "
                f"(0..{len(lines)})"
            )
        new_lines = lines[:insert_line] + [insert_text] + lines[insert_line:]
        target.write_text("".join(new_lines), encoding="utf-8")
        return f"insert ok in {raw_path}"

    def _delete_path(self, raw_path: str) -> str:
        target = self._resolve(raw_path)
        self._assert_write_allowed(target)
        if target.is_dir():
            raise ValueError(f"refusing to delete directory {raw_path}")
        target.unlink()
        return f"deleted {raw_path}"

    def _rename_path(self, old_raw: str, new_raw: str) -> str:
        old_target = self._resolve(old_raw)
        new_target = self._resolve(new_raw)
        self._assert_write_allowed(old_target)
        self._assert_write_allowed(new_target)
        new_target.parent.mkdir(parents=True, exist_ok=True)
        old_target.rename(new_target)
        return f"renamed {old_raw} -> {new_raw}"

    # ─── manifest-aware helpers ────────────────────────────────────────

    def write_lesson(self, *, slug: str, summary: str, body: str) -> str:
        """High-level helper: write a lesson under the agent's namespace AND
        upsert the manifest entry. Used by agents that don't speak the tool
        protocol (vault_synthesizer) or that want to record a lesson outside
        the LLM loop (deterministic post-run signals)."""
        if "/" in slug or slug.startswith("."):
            raise ValueError(f"invalid slug: {slug}")
        raw_path = f"{self._agent_id}/{slug}.md"
        self._create_path(raw_path, body)
        _update_manifest_section(
            self._mount_root / "MEMORY_INDEX.md",
            agent_id=self._agent_id,
            slug=slug,
            summary=summary,
        )
        return f"wrote lesson {raw_path} + manifest"

    def promote_to_shared(self, *, slug: str) -> str:
        """Copy {agent_id}/{slug}.md → shared/from-{agent_id}-{slug}.md
        with provenance frontmatter. Explicit cross-agent publication
        — never automatic; agents must call this deliberately."""
        src = self._resolve(f"{self._agent_id}/{slug}.md")
        if not src.exists():
            raise ValueError(f"source lesson does not exist: {self._agent_id}/{slug}.md")
        dest_slug = f"from-{self._agent_id}-{slug}"
        provenance = (
            f"---\n"
            f"promoted_from: {self._agent_id}/{slug}.md\n"
            f"promoted_at: {date.today().isoformat()}\n"
            f"---\n\n"
        )
        body = provenance + src.read_text(encoding="utf-8")
        dest = self._mount_root / "shared" / f"{dest_slug}.md"
        dest.write_text(body, encoding="utf-8")
        _update_manifest_section(
            self._mount_root / "MEMORY_INDEX.md",
            agent_id="shared",
            slug=dest_slug,
            summary=f"promoted from {self._agent_id}/{slug}",
        )
        return f"promoted {self._agent_id}/{slug} -> shared/{dest_slug}"

    # ─── BetaAbstractMemoryTool overrides (thin dispatch) ──────────────

    def view(self, command: BetaMemoryTool20250818ViewCommand) -> str:
        return self._view_path(command.path)

    def create(self, command: BetaMemoryTool20250818CreateCommand) -> str:
        return self._create_path(command.path, command.file_text)

    def str_replace(self, command: BetaMemoryTool20250818StrReplaceCommand) -> str:
        return self._str_replace_path(command.path, command.old_str, command.new_str)

    def insert(self, command: BetaMemoryTool20250818InsertCommand) -> str:
        return self._insert_path(command.path, command.insert_line, command.insert_text)

    def delete(self, command: BetaMemoryTool20250818DeleteCommand) -> str:
        return self._delete_path(command.path)

    def rename(self, command: BetaMemoryTool20250818RenameCommand) -> str:
        return self._rename_path(command.old_path, command.new_path)


_MANIFEST_LINE_RE_TEMPLATE = r"^- {slug}:.*$"


def _update_manifest_section(
    manifest_path: Path,
    *,
    agent_id: str,
    slug: str,
    summary: str,
) -> None:
    """Idempotently upsert a `- {slug}: {summary}` line under `## {agent_id}`.

    Serialized via FileLock so multiple agents writing concurrently can't
    interleave heading creation. Pure file I/O; never raises on missing
    sections — creates the section on first use.

    The lock file lives outside the mount (as a sibling of the mount root)
    so Obsidian-Git never picks it up — placing it inside would commit a
    0-byte file into the vault on every run.
    """
    mount_root = manifest_path.parent
    lock_path = mount_root.parent / f".{mount_root.name}-manifest.lock"
    lock = FileLock(lock_path, exclusive=True, timeout=10.0)
    with lock:
        body = manifest_path.read_text(encoding="utf-8") if manifest_path.exists() else MANIFEST_HEADER
        heading = f"## {agent_id}"
        line = f"- {slug}: {summary}"
        line_re = re.compile(
            _MANIFEST_LINE_RE_TEMPLATE.format(slug=re.escape(slug)),
            re.MULTILINE,
        )
        if heading not in body:
            body = body.rstrip() + f"\n\n{heading}\n\n{line}\n"
        elif line_re.search(body):
            body = line_re.sub(line, body)
        else:
            # Insert immediately under the heading.
            body = body.replace(heading + "\n", heading + "\n\n" + line + "\n", 1)
        manifest_path.write_text(body, encoding="utf-8")


def inject_memories_into_prompt(
    *,
    mount_root: Path,
    agent_id: str,
    enabled: bool,
    max_chars: int = 8000,
) -> str:
    """Read-only memory injection for agents that don't speak the tool protocol.

    Returns a single markdown string ready to prepend to an LLM prompt.
    Format:

        # Lessons remembered from prior runs

        ## Manifest

        {full MEMORY_INDEX.md body}

        ## Your namespace ({agent_id}/)

        {body of every .md file under {mount_root}/{agent_id}/}

        ## Shared lessons (shared/)

        {body of every .md file under {mount_root}/shared/}

    Truncates at `max_chars` and appends "(truncated)" if anything was cut.
    Returns "" when `enabled=False` — caller can unconditionally string-concat.
    """
    if not enabled:
        return ""
    parts: list[str] = ["# Lessons remembered from prior runs\n"]
    manifest = mount_root / "MEMORY_INDEX.md"
    if manifest.exists():
        parts.append("## Manifest\n")
        parts.append(manifest.read_text(encoding="utf-8"))
    for label, ns in (("Your namespace", agent_id), ("Shared lessons", "shared")):
        ns_dir = mount_root / ns
        if not ns_dir.is_dir():
            continue
        parts.append(f"\n## {label} ({ns}/)\n")
        for f in sorted(ns_dir.glob("*.md")):
            parts.append(f"\n### {f.name}\n")
            parts.append(f.read_text(encoding="utf-8"))
    combined = "\n".join(parts)
    if len(combined) > max_chars:
        combined = combined[:max_chars] + "\n\n(truncated)\n"
    return combined
