"""Shared filesystem-memory layer for the agent fleet.

Subclasses Anthropic's BetaAbstractMemoryTool (memory_20250818) for cloud
agents and exposes a read-only `inject_memories_into_prompt()` helper for
local-Ollama agents that don't speak the tool protocol.

Mount: vault/90_system/fleet-memory/ (resolved from config.toml).
Namespacing: {mount}/{agent_id}/ for per-agent state, {mount}/shared/ for
cross-agent lessons. Promotion to shared is via explicit promote_to_shared()
call — never an implicit tool command.

Path traversal is the load-bearing safety check: every read/write goes
through _resolve_path(), which performs realpath + prefix containment.
Any attempt to escape the mount via .., absolute paths, or symlinks raises
PathEscapeError.

See agents-sdk/docs/plans/2026-05-27-fleet-memory-phase-1-plan.md.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger("fleet_memory")


class PathEscapeError(ValueError):
    """A memory command tried to access a path outside the mount root."""


def _resolve_path(mount_root: Path, raw_path: str) -> Path:
    """Resolve `raw_path` against `mount_root`, rejecting any escape.

    Args:
        mount_root: The fleet-memory mount directory. Must already exist.
        raw_path: A relative path the caller wants to access inside the mount.
            An empty string is rejected.

    Returns:
        The fully-resolved absolute path, guaranteed to live under
        `mount_root.resolve()`. The path itself may not exist yet (the
        memory-tool `create` command needs to write new files); the guard
        only ensures *where it would land* is inside the mount.

    Raises:
        PathEscapeError: If `raw_path` is empty, if it resolves outside the
            mount (via `..`, absolute path, or symlink chain), or if any
            intermediate component is a symlink pointing outside the mount.
    """
    if not raw_path:
        raise PathEscapeError("empty path")

    mount_real = mount_root.resolve()
    if not mount_real.exists():
        raise PathEscapeError(f"mount root does not exist: {mount_real}")

    candidate = (mount_real / raw_path).resolve()

    # Containment check via Path semantics (handles cross-platform separators
    # correctly; string prefix would false-positive on /tmp/fleet vs /tmp/fleet2).
    try:
        candidate.relative_to(mount_real)
    except ValueError as exc:
        raise PathEscapeError(
            f"path escapes mount: candidate={candidate} mount={mount_real}"
        ) from exc

    return candidate


MANIFEST_HEADER = (
    "# Fleet Memory Index\n\n"
    "_Auto-generated by lib.fleet_memory. Do not edit by hand._\n\n"
    "One-line summary per memory file. Used by agents for the\n"
    "manifest-then-top-5 retrieval pattern (Perplexity DR, Apr 2026).\n\n"
)


def ensure_mount(mount_root: Path, *, agent_ids: list[str]) -> None:
    """Create the mount layout idempotently.

    Layout:
        {mount_root}/
            shared/
            {agent_id}/         (one per id passed in)
            MEMORY_INDEX.md     (created with header if absent)

    Existing files are never overwritten. Safe to call on every run.
    """
    mount_root.mkdir(parents=True, exist_ok=True)
    (mount_root / "shared").mkdir(exist_ok=True)
    for aid in agent_ids:
        (mount_root / aid).mkdir(exist_ok=True)
    manifest = mount_root / "MEMORY_INDEX.md"
    if not manifest.exists():
        manifest.write_text(MANIFEST_HEADER, encoding="utf-8")


from anthropic.lib.tools import BetaAbstractMemoryTool
from anthropic.types.beta import (
    BetaMemoryTool20250818CreateCommand,
    BetaMemoryTool20250818DeleteCommand,
    BetaMemoryTool20250818InsertCommand,
    BetaMemoryTool20250818RenameCommand,
    BetaMemoryTool20250818StrReplaceCommand,
    BetaMemoryTool20250818ViewCommand,
)


class NamespaceViolation(ValueError):
    """A tool tried to write outside its agent_id namespace AND outside shared/."""


class FleetMemoryTool(BetaAbstractMemoryTool):
    """Per-agent memory tool scoped to {mount_root}/{agent_id}/ for writes.

    Reads are allowed from anywhere under the mount (so agents can see
    shared/ and peer namespaces); writes are restricted to the agent's
    own namespace plus shared/. Use promote_to_shared() for an explicit,
    auditable promotion path.
    """

    def __init__(
        self,
        *,
        mount_root: Path,
        agent_id: str,
    ) -> None:
        super().__init__()
        if not agent_id:
            raise ValueError("agent_id is required")
        self._mount_root = mount_root
        self._agent_id = agent_id

    # ─── path discipline helpers ───────────────────────────────────────

    def _resolve(self, raw_path: str) -> Path:
        # Strip any leading "/memories/" prefix the Anthropic protocol uses.
        # Agents see paths as "/memories/vault_synthesizer/foo.md" but on
        # disk we mount at {mount_root}/vault_synthesizer/foo.md.
        relpath = raw_path.lstrip("/")
        if relpath.startswith("memories/"):
            relpath = relpath[len("memories/"):]
        return _resolve_path(self._mount_root, relpath)

    def _assert_write_allowed(self, target: Path) -> None:
        rel = target.relative_to(self._mount_root.resolve())
        first = rel.parts[0] if rel.parts else ""
        if first == self._agent_id or first == "shared":
            return
        raise NamespaceViolation(
            f"agent={self._agent_id} tried to write {rel} — only "
            f"{self._agent_id}/** and shared/** are writable"
        )

    # ─── internal command implementations (testable without SDK objects) ──

    def _view_path(self, raw_path: str) -> str:
        target = self._resolve(raw_path)
        if target.is_dir():
            entries = sorted(p.name for p in target.iterdir())
            return "\n".join(entries) if entries else "(empty)"
        return target.read_text(encoding="utf-8")

    def _create_path(self, raw_path: str, body: str) -> str:
        target = self._resolve(raw_path)
        self._assert_write_allowed(target)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        return f"created {target.relative_to(self._mount_root.resolve())}"

    # ─── BetaAbstractMemoryTool overrides (thin dispatch) ──────────────

    def view(self, command: BetaMemoryTool20250818ViewCommand) -> str:
        return self._view_path(command.path)

    def create(self, command: BetaMemoryTool20250818CreateCommand) -> str:
        return self._create_path(command.path, command.file_text)

    # The remaining four are stubs until Task 5 lands them.
    def str_replace(self, command: BetaMemoryTool20250818StrReplaceCommand) -> str:
        raise NotImplementedError("str_replace lands in Task 5")

    def insert(self, command: BetaMemoryTool20250818InsertCommand) -> str:
        raise NotImplementedError("insert lands in Task 5")

    def delete(self, command: BetaMemoryTool20250818DeleteCommand) -> str:
        raise NotImplementedError("delete lands in Task 5")

    def rename(self, command: BetaMemoryTool20250818RenameCommand) -> str:
        raise NotImplementedError("rename lands in Task 5")
