"""Tests for .claude/hooks/session-start-inject-index.sh (Phase B).

The hook is a bash script that emits a SessionStart `additionalContext`
JSON object on stdout, reading `vault/knowledge/index.md`.

Cases covered:
  - missing index file → empty-state stub
  - empty / placeholder-only index → empty-state stub
  - populated index ≤ max_chars → full content emitted
  - populated index > max_chars → budget respected, and the drop is announced
  - the compact row format that makes the budget go ~2.3x further (#202)
  - every concept survives a realistic budget (#202)
  - a truncated section is the newest rows, not the alphabetically first (#202)
  - JSON output schema matches the plan contract
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
HOOK = REPO_ROOT / ".claude" / "hooks" / "session-start-inject-index.sh"

EMPTY_STUB_MARKER = "knowledge index is empty"
HEADER_MARKER = "## Knowledge Index (vault/knowledge/index.md)"
TRUNCATION_MARKER = "not shown"
FOOTER_MARKER = "_To read any article"


def _index_body(ctx: str) -> str:
    """The rendered index between the wrapper header and footer."""
    body = ctx.split(HEADER_MARKER, 1)[1].lstrip("\n")
    return body.split(FOOTER_MARKER, 1)[0].rstrip("\n")


def _run_hook(*, index_path: Path | None, max_chars: int | None = None) -> dict:
    env = {
        "PATH": "/usr/bin:/bin:/usr/local/bin:/opt/homebrew/bin",
    }
    if index_path is not None:
        env["KNOWLEDGE_INDEX_PATH"] = str(index_path)
    if max_chars is not None:
        env["KNOWLEDGE_INDEX_MAX_CHARS"] = str(max_chars)
    proc = subprocess.run(
        ["bash", str(HOOK)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        input="",
        env=env,
    )
    assert proc.returncode == 0, (
        f"hook exited non-zero: {proc.returncode}\nstderr={proc.stderr!r}"
    )
    return json.loads(proc.stdout)


def test_missing_index_emits_empty_stub(tmp_path: Path) -> None:
    """If the index file does not exist, emit the empty-state stub."""
    missing = tmp_path / "vault" / "knowledge" / "index.md"
    out = _run_hook(index_path=missing)
    assert out["hookSpecificOutput"]["hookEventName"] == "SessionStart"
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert EMPTY_STUB_MARKER in ctx


def test_placeholder_index_emits_empty_stub(tmp_path: Path) -> None:
    """The default `_(none yet)_` placeholder index is treated as empty."""
    idx = tmp_path / "index.md"
    idx.write_text(
        "# Knowledge Index\n\n_Auto-generated by vault_synthesizer._\n\n"
        "## Concepts\n\n- _(none yet)_\n\n"
        "## Connections\n\n- _(none yet)_\n",
        encoding="utf-8",
    )
    out = _run_hook(index_path=idx)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert EMPTY_STUB_MARKER in ctx


def test_populated_index_emits_full_content(tmp_path: Path) -> None:
    """A populated index is wrapped with the header/footer and emitted in full."""
    idx = tmp_path / "index.md"
    body = (
        "# Knowledge Index\n\n"
        "## Concepts\n\n"
        "- [[concepts/error-handling]] — Sean's preferred error-handling idiom\n"
        "- [[concepts/retry-policy]] — exponential backoff with jitter\n\n"
        "## Connections\n\n"
        "- [[connections/error-and-retry]] — when to retry vs fail loud\n"
    )
    idx.write_text(body, encoding="utf-8")
    out = _run_hook(index_path=idx)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert HEADER_MARKER in ctx
    # Rows are compact slugs now, not wikilinks (#202): the slug is what a
    # reader needs to open the file, and the wikilink spends ~2.3x the
    # characters to say it twice.
    assert "- error-handling" in ctx
    assert "- retry-policy" in ctx
    assert "- error-and-retry" in ctx
    assert EMPTY_STUB_MARKER not in ctx


def test_oversize_index_respects_the_budget_and_says_what_it_dropped(
    tmp_path: Path,
) -> None:
    """Over-budget rendering stays inside the cap AND announces the drop.

    Supersedes an earlier test that asserted the emitted slice was
    *exactly* `cap` characters. That assertion pinned the defect in
    #202 as the contract: a blind `content[:cap]` prefix, which is how
    all 694 connection articles went missing from every session for
    five weeks without a word.
    """
    cap = 1500
    idx = tmp_path / "index.md"
    payload = "## Concepts\n\n"
    for i in range(400):
        payload += f"- [[concepts/concept-number-{i:04d}.md|Concept Number {i:04d}]]\n"
    idx.write_text(payload, encoding="utf-8")
    out = _run_hook(index_path=idx, max_chars=cap)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    rendered = _index_body(ctx)
    assert len(rendered) <= cap, f"rendered {len(rendered)} chars over cap {cap}"
    assert TRUNCATION_MARKER in ctx, "a dropped row must never be silent"
    assert "of 400" in ctx, "the notice must carry the real total"


def test_json_output_schema_is_strict(tmp_path: Path) -> None:
    """Output JSON has exactly the plan-required schema."""
    idx = tmp_path / "index.md"
    idx.write_text("## Concepts\n\n- [[concepts/x]] hi\n", encoding="utf-8")
    out = _run_hook(index_path=idx)
    # Top-level: only hookSpecificOutput.
    assert set(out.keys()) == {"hookSpecificOutput"}
    inner = out["hookSpecificOutput"]
    # Inner: exactly hookEventName + additionalContext.
    assert set(inner.keys()) == {"hookEventName", "additionalContext"}
    assert inner["hookEventName"] == "SessionStart"
    assert isinstance(inner["additionalContext"], str)
    assert len(inner["additionalContext"]) > 0


def _write_index(idx: Path, *, concepts: int, connections: int) -> None:
    """A structurally real index: two sections, wikilink rows, sorted."""
    body = ["# Knowledge Index\n", "_Auto-generated by vault_synthesizer._\n", "\n## Concepts\n"]
    body += [
        f"- [[concepts/concept-{i:04d}.md|Concept {i:04d}]]" for i in range(concepts)
    ]
    body.append("\n## Connections\n")
    body += [
        f"- [[connections/connection-{i:04d}.md|Connection {i:04d}]]"
        for i in range(connections)
    ]
    idx.write_text("\n".join(body) + "\n", encoding="utf-8")


def test_compact_rows_beat_the_wikilink_format_on_coverage(tmp_path: Path) -> None:
    """The compact format must fit strictly more rows than wikilinks did.

    This is the whole reason #202 is fixable without spending more
    tokens: the wikilink says the slug twice, once as a path and once
    as a title, and the budget pays for both.
    """
    idx = tmp_path / "index.md"
    _write_index(idx, concepts=218, connections=694)
    out = _run_hook(index_path=idx, max_chars=15000)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    rows = [ln for ln in ctx.splitlines() if ln.startswith("- ")]
    assert "[[" not in ctx, "wikilink syntax should be gone from the injected block"
    # The old format fit 190 rows in this budget. Anything at or below
    # that means the reformat bought nothing.
    assert len(rows) > 190, f"compact format fit only {len(rows)} rows"


def test_every_concept_survives_a_realistic_budget(tmp_path: Path) -> None:
    """All 218 concepts fit in the unchanged 15,000-char cap.

    The measured reason #202 needs no cap increase: the full concept
    list renders in ~7,100 characters, under half the existing budget.
    """
    idx = tmp_path / "index.md"
    _write_index(idx, concepts=218, connections=694)
    out = _run_hook(index_path=idx, max_chars=15000)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    missing = [i for i in range(218) if f"- concept-{i:04d}" not in ctx]
    assert not missing, f"{len(missing)} concepts dropped, first={missing[:3]}"


def test_connections_reach_the_session_at_all(tmp_path: Path) -> None:
    """The regression #202 exists to kill: zero connections injected."""
    idx = tmp_path / "index.md"
    _write_index(idx, concepts=218, connections=694)
    out = _run_hook(index_path=idx, max_chars=15000)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    shown = [i for i in range(694) if f"- connection-{i:04d}" in ctx]
    assert shown, "no connection article reached the session"


def test_a_truncated_section_shows_the_newest_rows(tmp_path: Path) -> None:
    """Partial coverage is the newest rows, not the alphabetical head.

    An alphabetical prefix represents the graph by whatever starts with
    'a'. Recency at least answers "what did the fleet write lately",
    which is what the injection is for.
    """
    idx = tmp_path / "index.md"
    _write_index(idx, concepts=5, connections=60)
    conns = tmp_path / "connections"
    conns.mkdir()
    for i in range(60):
        # connection-0059 is newest, connection-0000 oldest.
        (conns / f"connection-{i:04d}.md").write_text(
            "---\n"
            f'title: "Connection {i:04d}"\n'
            f"created: 2026-{1 + i // 28:02d}-{1 + i % 28:02d}\n"
            "---\n",
            encoding="utf-8",
        )
    out = _run_hook(index_path=idx, max_chars=900)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert TRUNCATION_MARKER in ctx
    assert "- connection-0059" in ctx, "the newest connection was dropped"
    assert "- connection-0000" not in ctx, "the oldest connection was kept"


def test_recency_reads_frontmatter_not_mtime(tmp_path: Path) -> None:
    """mtime must not decide what survives.

    A git checkout or a Mac Mini sync rewrites every mtime at once, and
    the real vault shows exactly that: 694 connection articles whose
    mtimes all land on the same day. Selection has to come from the
    `created:`/`updated:` fields the synthesizer writes, or the notice's
    "newest kept" claim is not true.
    """
    idx = tmp_path / "index.md"
    _write_index(idx, concepts=2, connections=40)
    conns = tmp_path / "connections"
    conns.mkdir()
    import os
    import time

    now = time.time()
    for i in range(40):
        f = conns / f"connection-{i:04d}.md"
        # Frontmatter says 0000 is newest; mtime says the exact reverse.
        rev = 39 - i
        f.write_text(
            f"---\ncreated: 2026-{1 + rev // 28:02d}-{1 + rev % 28:02d}\n---\n",
            encoding="utf-8",
        )
        os.utime(f, (now - (40 - i) * 3600, now - (40 - i) * 3600))
    out = _run_hook(index_path=idx, max_chars=700)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert TRUNCATION_MARKER in ctx
    assert "- connection-0000" in ctx, "frontmatter date did not win over mtime"
    assert "- connection-0039" not in ctx, "mtime drove the selection"


def test_a_complete_render_makes_no_truncation_claim(tmp_path: Path) -> None:
    """No notice when nothing was dropped: the notice must mean something."""
    idx = tmp_path / "index.md"
    _write_index(idx, concepts=3, connections=3)
    out = _run_hook(index_path=idx, max_chars=15000)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert TRUNCATION_MARKER not in ctx


def test_unparseable_rows_pass_through_rather_than_vanish(tmp_path: Path) -> None:
    """A row the reformatter cannot read is kept, never silently dropped."""
    idx = tmp_path / "index.md"
    idx.write_text(
        "## Concepts\n\n"
        "- [[concepts/normal.md|Normal]]\n"
        "- some hand-written note that is not a wikilink row\n",
        encoding="utf-8",
    )
    out = _run_hook(index_path=idx, max_chars=15000)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert "- normal" in ctx
    assert "some hand-written note that is not a wikilink row" in ctx
