"""Tests for .claude/hooks/session-start-inject-index.sh (Phase B).

The hook is a bash script that emits a SessionStart `additionalContext`
JSON object on stdout, reading `vault/knowledge/index.md`.

Cases covered:
  - missing index file → empty-state stub
  - empty / placeholder-only index → empty-state stub
  - populated index ≤ max_chars → full content emitted
  - populated index > max_chars → truncated to exactly max_chars
  - JSON output schema matches the plan contract
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
HOOK = REPO_ROOT / ".claude" / "hooks" / "session-start-inject-index.sh"

EMPTY_STUB_MARKER = "knowledge index is empty"
HEADER_MARKER = "## Knowledge Index (vault/knowledge/index.md)"


def _run_hook(*, index_path: Path | None, max_chars: int | None = None) -> dict:
    env = {
        "PATH": "/usr/bin:/bin:/usr/local/bin:/opt/homebrew/bin",
    }
    if index_path is not None:
        env["KNOWLEDGE_INDEX_PATH"] = str(index_path)
    if max_chars is not None:
        env["KNOWLEDGE_INDEX_MAX_CHARS"] = str(max_chars)
    proc = subprocess.run(
        ["bash", str(HOOK)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        input="",
        env=env,
    )
    assert proc.returncode == 0, (
        f"hook exited non-zero: {proc.returncode}\nstderr={proc.stderr!r}"
    )
    return json.loads(proc.stdout)


def test_missing_index_emits_empty_stub(tmp_path: Path) -> None:
    """If the index file does not exist, emit the empty-state stub."""
    missing = tmp_path / "vault" / "knowledge" / "index.md"
    out = _run_hook(index_path=missing)
    assert out["hookSpecificOutput"]["hookEventName"] == "SessionStart"
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert EMPTY_STUB_MARKER in ctx


def test_placeholder_index_emits_empty_stub(tmp_path: Path) -> None:
    """The default `_(none yet)_` placeholder index is treated as empty."""
    idx = tmp_path / "index.md"
    idx.write_text(
        "# Knowledge Index\n\n_Auto-generated by vault_synthesizer._\n\n"
        "## Concepts\n\n- _(none yet)_\n\n"
        "## Connections\n\n- _(none yet)_\n",
        encoding="utf-8",
    )
    out = _run_hook(index_path=idx)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert EMPTY_STUB_MARKER in ctx


def test_populated_index_emits_full_content(tmp_path: Path) -> None:
    """A populated index is wrapped with the header/footer and emitted in full."""
    idx = tmp_path / "index.md"
    body = (
        "# Knowledge Index\n\n"
        "## Concepts\n\n"
        "- [[concepts/error-handling]] — Sean's preferred error-handling idiom\n"
        "- [[concepts/retry-policy]] — exponential backoff with jitter\n\n"
        "## Connections\n\n"
        "- [[connections/error-and-retry]] — when to retry vs fail loud\n"
    )
    idx.write_text(body, encoding="utf-8")
    out = _run_hook(index_path=idx)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    assert HEADER_MARKER in ctx
    assert "[[concepts/error-handling]]" in ctx
    assert "[[connections/error-and-retry]]" in ctx
    assert EMPTY_STUB_MARKER not in ctx


def test_oversize_index_truncated_to_exact_char_cap(tmp_path: Path) -> None:
    """A 30,000-char index gets truncated to exactly KNOWLEDGE_INDEX_MAX_CHARS."""
    cap = 1500
    idx = tmp_path / "index.md"
    # Make sure this looks like a real index (has a wikilink so it's not
    # treated as empty), then pad with concept-link lines until well past cap.
    payload = "## Concepts\n\n"
    line = "- [[concepts/x]] padding for truncation test\n"
    while len(payload) < cap * 4:
        payload += line
    idx.write_text(payload, encoding="utf-8")
    out = _run_hook(index_path=idx, max_chars=cap)
    ctx = out["hookSpecificOutput"]["additionalContext"]
    # The cap applies to the index slice only — the wrapper header/footer
    # add fixed extra characters. Check that the slice is exactly `cap`.
    # We can pin this by looking for the truncation: the original payload
    # was at least 4*cap chars, so any cap-bounded slice is far smaller.
    assert HEADER_MARKER in ctx
    body_after_header = ctx.split(HEADER_MARKER, 1)[1].lstrip("\n")
    # The "_To read any article..." footer marks the slice end.
    footer = "_To read any article"
    slice_text = body_after_header.split(footer, 1)[0].rstrip("\n")
    assert len(slice_text) == cap, (
        f"expected slice exactly {cap} chars, got {len(slice_text)}"
    )


def test_json_output_schema_is_strict(tmp_path: Path) -> None:
    """Output JSON has exactly the plan-required schema."""
    idx = tmp_path / "index.md"
    idx.write_text("## Concepts\n\n- [[concepts/x]] hi\n", encoding="utf-8")
    out = _run_hook(index_path=idx)
    # Top-level: only hookSpecificOutput.
    assert set(out.keys()) == {"hookSpecificOutput"}
    inner = out["hookSpecificOutput"]
    # Inner: exactly hookEventName + additionalContext.
    assert set(inner.keys()) == {"hookEventName", "additionalContext"}
    assert inner["hookEventName"] == "SessionStart"
    assert isinstance(inner["additionalContext"], str)
    assert len(inner["additionalContext"]) > 0
