"""Tests for scripts.query — Phase C two-pass Q&A + C.M1/C.M2 provenance."""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from scripts.query import (
    ConsultedArticle,
    QueryResult,
    append_manifest,
    build_answer_prompt,
    build_selection_prompt,
    compute_chunk_id,
    format_qa_article,
    is_empty_index,
    load_articles,
    lookup_chunk_id_for_file,
    parse_index,
    run_query,
    run_selection_pass,
    slugify,
    write_qa_article,
)


# ─── helpers ──────────────────────────────────────────────────────────────


def _make_vault(tmp_path: Path, articles: dict[str, str], index_text: str) -> Path:
    vault = tmp_path / "vault"
    knowledge = vault / "knowledge"
    knowledge.mkdir(parents=True)
    (knowledge / "index.md").write_text(index_text, encoding="utf-8")
    for rel, body in articles.items():
        path = knowledge / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
    return vault


_POPULATED_INDEX = (
    "# Knowledge Index\n\n"
    "_Auto-generated by vault_synthesizer. Do not edit by hand._\n\n"
    "## Concepts\n\n"
    "- [[concepts/error-handling.md|Error Handling]]\n"
    "- [[concepts/cache-invalidation.md|Cache Invalidation]]\n\n"
    "## Connections\n\n"
    "- [[connections/error-cache-link.md|Error & Cache Link]]\n"
)

_EMPTY_INDEX = (
    "# Knowledge Index\n\n"
    "_Auto-generated by vault_synthesizer. Do not edit by hand._\n\n"
    "## Concepts\n\n- _(none yet)_\n\n"
    "## Connections\n\n- _(none yet)_\n"
)


def _articles_three() -> dict[str, str]:
    return {
        "concepts/error-handling.md": (
            "---\ntitle: \"Error Handling\"\ntype: concept\n---\n\n"
            "Body explaining error handling. [[concepts/cache-invalidation]]\n"
        ),
        "concepts/cache-invalidation.md": (
            "---\ntitle: \"Cache Invalidation\"\ntype: concept\n---\n\n"
            "Body. [[concepts/error-handling]]\n"
        ),
        "connections/error-cache-link.md": (
            "---\ntitle: \"Error & Cache Link\"\ntype: connection\n---\n\n"
            "Body. [[concepts/error-handling]] [[concepts/cache-invalidation]]\n"
        ),
    }


# ─── pure helper unit tests ───────────────────────────────────────────────


def test_slugify_basic() -> None:
    assert slugify("What's My Error Handling Pattern?") == "what-s-my-error-handling-pattern"
    assert slugify("    ") == "untitled"
    assert slugify("a"*200).startswith("a") and len(slugify("a"*200)) == 80


def test_compute_chunk_id_is_stable_and_12_hex() -> None:
    cid = compute_chunk_id("knowledge/concepts/foo.md", 0)
    assert len(cid) == 12
    assert all(c in "0123456789abcdef" for c in cid)
    assert compute_chunk_id("knowledge/concepts/foo.md", 0) == cid
    assert compute_chunk_id("knowledge/concepts/foo.md", 1) != cid


def test_parse_index_extracts_path_title_pairs() -> None:
    entries = parse_index(_POPULATED_INDEX)
    paths = {e["path"] for e in entries}
    titles = {e["title"] for e in entries}
    assert "concepts/error-handling.md" in paths
    assert "connections/error-cache-link.md" in paths
    assert "Error Handling" in titles


def test_parse_index_handles_empty_state_stub() -> None:
    entries = parse_index(_EMPTY_INDEX)
    assert entries == []
    assert is_empty_index(entries) is True


def test_parse_index_appends_md_when_missing() -> None:
    text = "## Concepts\n\n- [[concepts/foo|Foo]]\n"
    entries = parse_index(text)
    assert entries == [{"path": "concepts/foo.md", "title": "Foo"}]


def test_lookup_chunk_id_for_file(tmp_path: Path) -> None:
    db_path = tmp_path / ".vault-index.db"
    conn = sqlite3.connect(str(db_path))
    conn.execute(
        """CREATE TABLE chunks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            file_path TEXT NOT NULL,
            chunk_index INTEGER NOT NULL,
            chunk_text TEXT NOT NULL,
            embedding BLOB,
            file_mtime REAL NOT NULL,
            indexed_at TEXT NOT NULL,
            UNIQUE(file_path, chunk_index)
        )"""
    )
    conn.execute(
        "INSERT INTO chunks VALUES (NULL, ?, ?, ?, NULL, 0, '2026-05-01')",
        ("knowledge/concepts/error-handling.md", 0, "first chunk"),
    )
    conn.execute(
        "INSERT INTO chunks VALUES (NULL, ?, ?, ?, NULL, 0, '2026-05-01')",
        ("knowledge/concepts/error-handling.md", 1, "second chunk"),
    )
    conn.commit()
    conn.close()

    cid = lookup_chunk_id_for_file(db_path, "knowledge/concepts/error-handling.md")
    assert cid == compute_chunk_id("knowledge/concepts/error-handling.md", 0)

    # Missing file → None
    assert lookup_chunk_id_for_file(db_path, "knowledge/concepts/missing.md") is None

    # Missing DB → None
    assert lookup_chunk_id_for_file(tmp_path / "nope.db", "anything.md") is None


def test_build_selection_prompt_lists_articles_and_max() -> None:
    entries = parse_index(_POPULATED_INDEX)
    prompt = build_selection_prompt(question="Q?", index_entries=entries, max_articles=5)
    assert "Q?" in prompt
    assert "concepts/error-handling.md :: Error Handling" in prompt
    assert "Pick up to 5 articles" in prompt
    assert "\"selected\"" in prompt


def test_build_answer_prompt_truncates_long_bodies() -> None:
    # Use a marker char that can't appear elsewhere in the prompt template
    # so the truncation cap is unambiguous.
    body = "@" * 9000
    prompt = build_answer_prompt(question="Q?", articles=[("concepts/foo.md", body)])
    assert "concepts/foo.md" in prompt
    # build_answer_prompt slices body[:3500]; assert that exact cap
    assert prompt.count("@") == 3500


# ─── selection-pass behavior ──────────────────────────────────────────────


def test_run_selection_pass_filters_invalid_paths_and_clamps_similarity() -> None:
    def fake_llm(prompt: str, max_tokens: int) -> dict:
        return {
            "selected": [
                {"path": "concepts/error-handling.md", "similarity": 0.83},
                {"path": "concepts/error-handling.md", "similarity": 0.5},  # dup, drop
                {"path": "concepts/missing.md", "similarity": 0.99},        # invalid, drop
                {"path": "connections/error-cache-link.md", "similarity": 1.5},  # clamp to 1.0
                {"not_a_dict": True},                                       # malformed
            ]
        }

    consulted, entries = run_selection_pass(
        question="Q?",
        index_text=_POPULATED_INDEX,
        llm_caller=fake_llm,
        max_articles=10,
        selection_max_tokens=500,
    )
    paths = [c.path for c in consulted]
    assert paths == ["concepts/error-handling.md", "connections/error-cache-link.md"]
    assert consulted[0].similarity == 0.83
    assert consulted[1].similarity == 1.0
    assert len(entries) == 3


def test_run_selection_pass_returns_empty_on_empty_index() -> None:
    def llm_should_not_run(prompt: str, max_tokens: int) -> dict:
        raise AssertionError("selection pass must not invoke LLM on empty index")

    consulted, entries = run_selection_pass(
        question="anything",
        index_text=_EMPTY_INDEX,
        llm_caller=llm_should_not_run,
        max_articles=10,
        selection_max_tokens=500,
    )
    assert consulted == []
    assert entries == []


def test_run_selection_pass_swallows_llm_exception() -> None:
    def boom(prompt: str, max_tokens: int) -> dict:
        raise RuntimeError("upstream timeout")

    consulted, _entries = run_selection_pass(
        question="Q?",
        index_text=_POPULATED_INDEX,
        llm_caller=boom,
        max_articles=5,
        selection_max_tokens=500,
    )
    assert consulted == []


def test_run_selection_pass_respects_max_articles_cap() -> None:
    def fake_llm(prompt: str, max_tokens: int) -> dict:
        return {
            "selected": [
                {"path": "concepts/error-handling.md", "similarity": 0.9},
                {"path": "concepts/cache-invalidation.md", "similarity": 0.8},
                {"path": "connections/error-cache-link.md", "similarity": 0.7},
            ]
        }

    consulted, _ = run_selection_pass(
        question="Q?",
        index_text=_POPULATED_INDEX,
        llm_caller=fake_llm,
        max_articles=2,
        selection_max_tokens=500,
    )
    assert len(consulted) == 2


# ─── load_articles + chunk_id stamping ────────────────────────────────────


def test_load_articles_stamps_chunk_id_from_db(tmp_path: Path) -> None:
    vault = _make_vault(tmp_path, _articles_three(), _POPULATED_INDEX)
    knowledge = vault / "knowledge"
    db_path = vault / ".vault-index.db"
    conn = sqlite3.connect(str(db_path))
    conn.execute(
        """CREATE TABLE chunks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            file_path TEXT NOT NULL,
            chunk_index INTEGER NOT NULL,
            chunk_text TEXT NOT NULL,
            embedding BLOB,
            file_mtime REAL NOT NULL,
            indexed_at TEXT NOT NULL,
            UNIQUE(file_path, chunk_index)
        )"""
    )
    conn.execute(
        "INSERT INTO chunks VALUES (NULL, ?, ?, ?, NULL, 0, '2026-05-01')",
        ("knowledge/concepts/error-handling.md", 0, "body"),
    )
    conn.commit()
    conn.close()

    consulted = [
        ConsultedArticle(path="concepts/error-handling.md", chunk_id="", similarity=0.9),
        ConsultedArticle(path="concepts/cache-invalidation.md", chunk_id="", similarity=0.7),
    ]
    pairs = load_articles(knowledge, consulted, db_path)
    assert len(pairs) == 2
    assert all(c.chunk_id for c in consulted)  # both got stamped
    # First one matches the DB-driven id; second one falls back to deterministic
    expected_db = compute_chunk_id("knowledge/concepts/error-handling.md", 0)
    assert consulted[0].chunk_id == expected_db
    expected_fallback = compute_chunk_id("knowledge/concepts/cache-invalidation.md", 0)
    assert consulted[1].chunk_id == expected_fallback


def test_load_articles_skips_missing_files_but_still_stamps_chunk_id(tmp_path: Path) -> None:
    vault = _make_vault(tmp_path, {}, _POPULATED_INDEX)
    knowledge = vault / "knowledge"
    consulted = [ConsultedArticle(path="concepts/nonexistent.md", chunk_id="", similarity=0.5)]
    pairs = load_articles(knowledge, consulted, db_path=None)
    assert pairs == []
    # Frontmatter still needs a stable chunk_id even if the file vanished
    assert consulted[0].chunk_id == compute_chunk_id("knowledge/concepts/nonexistent.md", 0)


# ─── qa/ writer (C.M1) + manifest (C.M2) ──────────────────────────────────


def test_format_qa_article_includes_c_m1_frontmatter() -> None:
    consulted = [
        ConsultedArticle(path="concepts/error-handling.md", chunk_id="abc123def456",
                         similarity=0.83, title="Error Handling"),
        ConsultedArticle(path="connections/error-cache-link.md", chunk_id="78bc4f2e1a8d",
                         similarity=0.71, title="Error & Cache Link"),
    ]
    body = format_qa_article(
        question="What's my error handling pattern?",
        answer="See [[concepts/error-handling]] for the canonical pattern.",
        consulted=consulted,
        model="qwen3-14b",
        today="2026-05-01",
        synth_run="2026-05-01T14:30:12-04:00",
    )
    assert body.startswith("---")
    assert 'type: qa' in body
    assert 'model: qwen3-14b' in body
    assert 'synth_run: 2026-05-01T14:30:12-04:00' in body
    assert 'filed: 2026-05-01' in body
    assert 'chunk_id: abc123def456' in body
    assert 'similarity: 0.83' in body
    assert '[[concepts/error-handling]]' in body
    assert '## Answer' in body
    assert '## Consulted articles' in body


def test_write_qa_article_creates_file_with_kebab_slug(tmp_path: Path) -> None:
    qa_dir = tmp_path / "vault" / "knowledge" / "qa"
    consulted = [
        ConsultedArticle(path="concepts/error-handling.md", chunk_id="abc123def456",
                         similarity=0.83),
    ]
    path = write_qa_article(
        qa_dir=qa_dir,
        question="What's my error handling pattern?",
        answer="Use the local-first router. [[concepts/error-handling]]",
        consulted=consulted,
        model="qwen3-14b",
        synth_run="2026-05-01T14:30:12-04:00",
        now_iso="2026-05-01",
    )
    assert path.exists()
    assert path.name == "what-s-my-error-handling-pattern.md"
    text = path.read_text(encoding="utf-8")
    assert text.startswith("---")
    assert "chunk_id: abc123def456" in text


def test_append_manifest_appends_one_line_per_call(tmp_path: Path) -> None:
    manifest = tmp_path / ".manifest.json"
    append_manifest(manifest_path=manifest, record={"run_id": "a", "question": "q1"})
    append_manifest(manifest_path=manifest, record={"run_id": "b", "question": "q2"})
    lines = manifest.read_text(encoding="utf-8").splitlines()
    assert len(lines) == 2
    assert json.loads(lines[0])["question"] == "q1"
    assert json.loads(lines[1])["question"] == "q2"


# ─── run_query end-to-end (mocked LLM) ────────────────────────────────────


def test_run_query_happy_path_with_file_back(tmp_path: Path) -> None:
    vault = _make_vault(tmp_path, _articles_three(), _POPULATED_INDEX)

    def fake_selection(prompt: str, max_tokens: int) -> dict:
        return {
            "selected": [
                {"path": "concepts/error-handling.md", "similarity": 0.83},
                {"path": "connections/error-cache-link.md", "similarity": 0.71},
            ]
        }

    def fake_answer(prompt: str, max_tokens: int) -> str:
        # Validate the answer prompt was built with the article bodies present
        assert "Error Handling" in prompt or "concepts/error-handling.md" in prompt
        return "Yes — see [[concepts/error-handling]]."

    qa_dir = vault / "knowledge" / "qa"
    manifest = qa_dir / ".manifest.json"
    result = run_query(
        question="What's my error handling pattern?",
        vault_root=vault,
        selection_caller=fake_selection,
        answer_caller=fake_answer,
        file_back=True,
        max_articles=5,
        qa_dir=qa_dir,
        manifest_path=manifest,
        db_path=None,
        model_label="qwen3-14b",
        model_route="auto→local",
        now_iso="2026-05-01T14:30:12-04:00",
    )

    assert isinstance(result, QueryResult)
    assert "[[concepts/error-handling]]" in result.answer
    assert len(result.consulted) == 2
    assert result.consulted[0].path == "concepts/error-handling.md"
    assert all(c.chunk_id for c in result.consulted)
    assert result.qa_file is not None
    assert result.qa_file.exists()
    assert result.qa_file.parent == qa_dir
    assert not result.empty_index

    # qa/ frontmatter shape (C.M1)
    qa_text = result.qa_file.read_text(encoding="utf-8")
    assert "model: qwen3-14b" in qa_text
    assert "chunk_id:" in qa_text
    assert "similarity: 0.83" in qa_text
    assert "synth_run: 2026-05-01T14:30:12-04:00" in qa_text

    # Manifest (C.M2): exactly one line, valid JSON, expected keys
    lines = manifest.read_text(encoding="utf-8").splitlines()
    assert len(lines) == 1
    record = json.loads(lines[0])
    assert record["question"] == "What's my error handling pattern?"
    assert record["model"] == "qwen3-14b"
    assert record["model_route"] == "auto→local"
    assert record["qa_file"].endswith(".md")
    assert len(record["consulted"]) == 2
    assert {"path", "chunk_id", "similarity"} <= set(record["consulted"][0])


def test_run_query_empty_index_produces_clean_report_no_qa_file(tmp_path: Path) -> None:
    vault = _make_vault(tmp_path, {}, _EMPTY_INDEX)

    def selection_should_not_run(prompt: str, max_tokens: int) -> dict:
        raise AssertionError("selection caller must not run when index is empty")

    def answer_should_not_run(prompt: str, max_tokens: int) -> str:
        raise AssertionError("answer caller must not run when index is empty")

    qa_dir = vault / "knowledge" / "qa"
    manifest = qa_dir / ".manifest.json"
    result = run_query(
        question="Anything?",
        vault_root=vault,
        selection_caller=selection_should_not_run,
        answer_caller=answer_should_not_run,
        file_back=True,  # even with --file-back, empty index → no write
        qa_dir=qa_dir,
        manifest_path=manifest,
        db_path=None,
        model_label="qwen3-14b",
        model_route="auto→local",
    )

    assert result.empty_index is True
    assert result.consulted == []
    assert result.qa_file is None
    assert "No knowledge articles match" in result.answer
    assert not qa_dir.exists() or not any(qa_dir.iterdir())
    assert not manifest.exists()


def test_run_query_missing_index_file_returns_helpful_message(tmp_path: Path) -> None:
    vault = tmp_path / "vault"
    (vault / "knowledge").mkdir(parents=True)  # but no index.md

    def llm(prompt: str, max_tokens: int) -> dict:
        raise AssertionError("LLM should not run when index.md is missing")

    result = run_query(
        question="Q?",
        vault_root=vault,
        selection_caller=llm,
        answer_caller=lambda p, m: "",
        file_back=False,
    )
    assert result.empty_index is True
    assert "vault/knowledge/index.md" in result.answer
    assert "vault_synthesizer.py" in result.answer
    assert result.warnings == ["index.md missing"]


def test_run_query_no_file_back_still_returns_consulted(tmp_path: Path) -> None:
    vault = _make_vault(tmp_path, _articles_three(), _POPULATED_INDEX)

    def fake_selection(prompt: str, max_tokens: int) -> dict:
        return {"selected": [{"path": "concepts/error-handling.md", "similarity": 0.9}]}

    def fake_answer(prompt: str, max_tokens: int) -> str:
        return "Cite [[concepts/error-handling]]."

    result = run_query(
        question="Q?",
        vault_root=vault,
        selection_caller=fake_selection,
        answer_caller=fake_answer,
        file_back=False,
        db_path=None,
    )
    assert result.qa_file is None
    assert len(result.consulted) == 1
    qa_dir = vault / "knowledge" / "qa"
    assert not qa_dir.exists()


def test_run_query_two_consecutive_file_back_runs_append_two_manifest_lines(tmp_path: Path) -> None:
    vault = _make_vault(tmp_path, _articles_three(), _POPULATED_INDEX)

    def fake_selection(prompt: str, max_tokens: int) -> dict:
        return {"selected": [{"path": "concepts/error-handling.md", "similarity": 0.5}]}

    def fake_answer(prompt: str, max_tokens: int) -> str:
        return "[[concepts/error-handling]]"

    qa_dir = vault / "knowledge" / "qa"
    manifest = qa_dir / ".manifest.json"

    for q, run in [("Question one?", "2026-05-01T14:00:00"),
                   ("Question two?", "2026-05-01T14:15:00")]:
        run_query(
            question=q,
            vault_root=vault,
            selection_caller=fake_selection,
            answer_caller=fake_answer,
            file_back=True,
            qa_dir=qa_dir,
            manifest_path=manifest,
            db_path=None,
            model_label="qwen3-14b",
            model_route="auto→local",
            now_iso=run,
        )

    lines = manifest.read_text(encoding="utf-8").splitlines()
    assert len(lines) == 2
    questions = [json.loads(l)["question"] for l in lines]
    assert questions == ["Question one?", "Question two?"]
    qa_files = sorted(p.name for p in qa_dir.glob("*.md"))
    assert qa_files == ["question-one.md", "question-two.md"]
