"""Tests for lib.fleet_memory — shared filesystem-memory layer."""

from __future__ import annotations

import os
from pathlib import Path

import pytest


class TestResolvePathGuard:
    """The path-traversal guard is non-negotiable per CLAUDE.md / synthesis Risk Register."""

    def test_simple_relative_path_resolves_under_mount(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        resolved = _resolve_path(mount, "agent_id/note.md")
        assert resolved == (mount / "agent_id/note.md").resolve()

    def test_dotdot_escape_raises(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path, PathEscapeError
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        with pytest.raises(PathEscapeError):
            _resolve_path(mount, "../../etc/passwd")

    def test_absolute_path_outside_mount_raises(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path, PathEscapeError
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        with pytest.raises(PathEscapeError):
            _resolve_path(mount, "/etc/passwd")

    def test_symlink_escape_raises(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path, PathEscapeError
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        outside = tmp_path / "outside"
        outside.mkdir()
        outside_file = outside / "secret.txt"
        outside_file.write_text("nope")
        link = mount / "evil_link"
        link.symlink_to(outside_file)
        with pytest.raises(PathEscapeError):
            _resolve_path(mount, "evil_link")

    def test_resolves_to_nonexistent_descendant(self, tmp_path: Path):
        """We must allow paths that don't exist yet (create command), as long
        as they would land under the mount."""
        from lib.fleet_memory import _resolve_path
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        resolved = _resolve_path(mount, "new_agent/new_lesson.md")
        assert str(resolved).startswith(str(mount.resolve()))
        assert not resolved.exists()

    def test_empty_path_raises(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path, PathEscapeError
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        with pytest.raises(PathEscapeError):
            _resolve_path(mount, "")


class TestEnsureMount:
    def test_creates_mount_and_namespaces_idempotently(self, tmp_path: Path):
        from lib.fleet_memory import ensure_mount
        mount = tmp_path / "fleet-memory"
        ensure_mount(mount, agent_ids=["vault_synthesizer", "daily_driver"])
        assert mount.is_dir()
        assert (mount / "shared").is_dir()
        assert (mount / "vault_synthesizer").is_dir()
        assert (mount / "daily_driver").is_dir()
        assert (mount / "MEMORY_INDEX.md").is_file()
        # Idempotent: a second call must not raise and must not clobber.
        (mount / "shared" / "marker.md").write_text("existing")
        ensure_mount(mount, agent_ids=["vault_synthesizer", "daily_driver"])
        assert (mount / "shared" / "marker.md").read_text() == "existing"

    def test_manifest_has_well_known_header(self, tmp_path: Path):
        from lib.fleet_memory import ensure_mount
        mount = tmp_path / "fleet-memory"
        ensure_mount(mount, agent_ids=["vault_synthesizer"])
        manifest = (mount / "MEMORY_INDEX.md").read_text()
        assert manifest.startswith("# Fleet Memory Index")
        assert "_Auto-generated by lib.fleet_memory" in manifest


class TestFleetMemoryToolViewCreate:
    def test_constructor_requires_agent_id(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        with pytest.raises(TypeError):
            FleetMemoryTool(mount_root=tmp_fleet_memory)  # type: ignore[call-arg]

    def test_view_lists_agent_namespace(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        ns = tmp_fleet_memory / "vault_synthesizer"
        (ns / "lesson-1.md").write_text("first")
        (ns / "lesson-2.md").write_text("second")
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        result = tool._view_path("vault_synthesizer/")
        assert "lesson-1.md" in result
        assert "lesson-2.md" in result

    def test_view_reads_file_body(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        ns = tmp_fleet_memory / "vault_synthesizer"
        (ns / "lesson.md").write_text("# Lesson\nDon't trust mock retrievers.\n")
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        result = tool._view_path("vault_synthesizer/lesson.md")
        assert "Lesson" in result
        assert "Don't trust mock retrievers." in result

    def test_view_rejects_path_escape(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool, PathEscapeError
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        with pytest.raises(PathEscapeError):
            tool._view_path("../../../etc/passwd")

    def test_create_writes_to_agent_namespace(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path(
            "vault_synthesizer/pr52-stale-checkout.md",
            "PR #52 wrote pre-Tier-2 articles. Always filter to manifest.",
        )
        on_disk = tmp_fleet_memory / "vault_synthesizer/pr52-stale-checkout.md"
        assert on_disk.read_text().startswith("PR #52")

    def test_create_rejects_writes_outside_own_namespace(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool, NamespaceViolation
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        # Synth must not write into daily_driver/ directly.
        with pytest.raises(NamespaceViolation):
            tool._create_path("daily_driver/sneaky.md", "no")

    def test_create_allows_writes_to_shared(self, tmp_fleet_memory: Path):
        """Writes to shared/ are *allowed* by the namespace guard — the actual
        promotion ergonomics live in the explicit promote_to_shared() helper
        (Task 7). But the tool isn't blocked from writing directly to shared/
        because that's how an agent flushes an already-validated lesson."""
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path("shared/cross-fleet-lesson.md", "All agents read this.")
        assert (tmp_fleet_memory / "shared/cross-fleet-lesson.md").exists()


class TestFleetMemoryToolRemainingCommands:
    def test_str_replace_replaces_unique_match(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path("vault_synthesizer/note.md", "Lesson: trust mocks.")
        tool._str_replace_path(
            "vault_synthesizer/note.md", "trust mocks", "do not trust mocks"
        )
        assert (tmp_fleet_memory / "vault_synthesizer/note.md").read_text() == (
            "Lesson: do not trust mocks."
        )

    def test_str_replace_raises_on_missing_old(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path("vault_synthesizer/note.md", "Lesson: trust mocks.")
        with pytest.raises(ValueError):
            tool._str_replace_path("vault_synthesizer/note.md", "missing-text", "x")

    def test_str_replace_raises_on_multiple_matches(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path("vault_synthesizer/note.md", "a a a")
        with pytest.raises(ValueError):
            tool._str_replace_path("vault_synthesizer/note.md", "a", "b")

    def test_insert_inserts_after_line_number(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path("vault_synthesizer/note.md", "line1\nline3\n")
        tool._insert_path("vault_synthesizer/note.md", insert_line=1, insert_text="line2\n")
        assert (tmp_fleet_memory / "vault_synthesizer/note.md").read_text() == (
            "line1\nline2\nline3\n"
        )

    def test_delete_removes_file(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path("vault_synthesizer/note.md", "x")
        tool._delete_path("vault_synthesizer/note.md")
        assert not (tmp_fleet_memory / "vault_synthesizer/note.md").exists()

    def test_delete_refuses_paths_outside_writable_namespaces(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool, NamespaceViolation
        # Create a peer file via direct disk write — simulating daily_driver's file.
        peer = tmp_fleet_memory / "daily_driver" / "peer.md"
        peer.write_text("peer")
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        with pytest.raises(NamespaceViolation):
            tool._delete_path("daily_driver/peer.md")

    def test_rename_moves_within_writable_namespaces(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path("vault_synthesizer/old.md", "x")
        tool._rename_path("vault_synthesizer/old.md", "vault_synthesizer/new.md")
        assert not (tmp_fleet_memory / "vault_synthesizer/old.md").exists()
        assert (tmp_fleet_memory / "vault_synthesizer/new.md").read_text() == "x"

    def test_rename_refuses_cross_namespace_target(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool, NamespaceViolation
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path("vault_synthesizer/x.md", "x")
        with pytest.raises(NamespaceViolation):
            tool._rename_path("vault_synthesizer/x.md", "daily_driver/x.md")


class TestManifestUpdate:
    def test_manifest_appends_entry_under_agent_heading(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool.write_lesson(
            slug="pr52-stale-checkout",
            summary="Filter critic candidates to synth manifest, not mtime.",
            body="# PR #52 Stale Checkout\n\nThe MBP runs a parallel pre-retrofit ...",
        )
        manifest = (tmp_fleet_memory / "MEMORY_INDEX.md").read_text()
        assert "## vault_synthesizer" in manifest
        assert "pr52-stale-checkout" in manifest
        assert "Filter critic candidates" in manifest

    def test_second_write_does_not_duplicate_heading(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool.write_lesson(slug="a", summary="A", body="A")
        tool.write_lesson(slug="b", summary="B", body="B")
        manifest = (tmp_fleet_memory / "MEMORY_INDEX.md").read_text()
        assert manifest.count("## vault_synthesizer") == 1

    def test_rewriting_same_slug_updates_in_place(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool.write_lesson(slug="x", summary="first version", body="A")
        tool.write_lesson(slug="x", summary="second version", body="B")
        manifest = (tmp_fleet_memory / "MEMORY_INDEX.md").read_text()
        assert manifest.count("- x:") == 1
        assert "second version" in manifest
        assert "first version" not in manifest

    def test_lock_file_lives_outside_mount(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool.write_lesson(slug="a", summary="A", body="A")
        # No lock file inside the mount
        assert not any(tmp_fleet_memory.glob("*.lock"))
        # Lock file does live next to the mount (sibling in vault/90_system/)
        expected_lock = tmp_fleet_memory.parent / f".{tmp_fleet_memory.name}-manifest.lock"
        assert expected_lock.exists()


class TestPromoteToShared:
    def test_promote_copies_file_to_shared_with_provenance(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool.write_lesson(slug="x", summary="X", body="content")
        tool.promote_to_shared(slug="x")
        shared = tmp_fleet_memory / "shared/from-vault_synthesizer-x.md"
        assert shared.exists()
        text = shared.read_text()
        assert "content" in text
        assert "promoted_from: vault_synthesizer/x.md" in text  # provenance frontmatter

    def test_promote_appends_to_shared_section_in_manifest(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool.write_lesson(slug="x", summary="X", body="content")
        tool.promote_to_shared(slug="x")
        manifest = (tmp_fleet_memory / "MEMORY_INDEX.md").read_text()
        assert "## shared" in manifest
        assert "from-vault_synthesizer-x" in manifest


class TestInjectMemoriesIntoPrompt:
    def test_returns_empty_when_disabled(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import inject_memories_into_prompt
        result = inject_memories_into_prompt(
            mount_root=tmp_fleet_memory, agent_id="vault_synthesizer", enabled=False
        )
        assert result == ""

    def test_returns_manifest_plus_own_namespace_bodies(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool, inject_memories_into_prompt
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool.write_lesson(slug="pr52", summary="PR52 lesson", body="filter to manifest")
        # Simulate a peer-written shared lesson:
        (tmp_fleet_memory / "shared/general.md").write_text("Trust no mock retriever.")
        result = inject_memories_into_prompt(
            mount_root=tmp_fleet_memory, agent_id="vault_synthesizer", enabled=True
        )
        assert "PR52 lesson" in result          # manifest summary visible
        assert "filter to manifest" in result   # own-namespace body included
        assert "Trust no mock retriever." in result  # shared/ body included

    def test_truncates_at_max_chars(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool, inject_memories_into_prompt
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool.write_lesson(slug="big", summary="big", body="x" * 50_000)
        result = inject_memories_into_prompt(
            mount_root=tmp_fleet_memory, agent_id="vault_synthesizer",
            enabled=True, max_chars=2000,
        )
        assert len(result) <= 2000 + 100  # +100 cushion for the truncation marker
        assert "(truncated)" in result
