"""Tests for lib.fleet_memory — shared filesystem-memory layer."""

from __future__ import annotations

import os
from pathlib import Path

import pytest


class TestResolvePathGuard:
    """The path-traversal guard is non-negotiable per CLAUDE.md / synthesis Risk Register."""

    def test_simple_relative_path_resolves_under_mount(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        resolved = _resolve_path(mount, "agent_id/note.md")
        assert resolved == (mount / "agent_id/note.md").resolve()

    def test_dotdot_escape_raises(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path, PathEscapeError
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        with pytest.raises(PathEscapeError):
            _resolve_path(mount, "../../etc/passwd")

    def test_absolute_path_outside_mount_raises(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path, PathEscapeError
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        with pytest.raises(PathEscapeError):
            _resolve_path(mount, "/etc/passwd")

    def test_symlink_escape_raises(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path, PathEscapeError
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        outside = tmp_path / "outside"
        outside.mkdir()
        outside_file = outside / "secret.txt"
        outside_file.write_text("nope")
        link = mount / "evil_link"
        link.symlink_to(outside_file)
        with pytest.raises(PathEscapeError):
            _resolve_path(mount, "evil_link")

    def test_resolves_to_nonexistent_descendant(self, tmp_path: Path):
        """We must allow paths that don't exist yet (create command), as long
        as they would land under the mount."""
        from lib.fleet_memory import _resolve_path
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        resolved = _resolve_path(mount, "new_agent/new_lesson.md")
        assert str(resolved).startswith(str(mount.resolve()))
        assert not resolved.exists()

    def test_empty_path_raises(self, tmp_path: Path):
        from lib.fleet_memory import _resolve_path, PathEscapeError
        mount = tmp_path / "fleet-memory"
        mount.mkdir()
        with pytest.raises(PathEscapeError):
            _resolve_path(mount, "")


class TestEnsureMount:
    def test_creates_mount_and_namespaces_idempotently(self, tmp_path: Path):
        from lib.fleet_memory import ensure_mount
        mount = tmp_path / "fleet-memory"
        ensure_mount(mount, agent_ids=["vault_synthesizer", "daily_driver"])
        assert mount.is_dir()
        assert (mount / "shared").is_dir()
        assert (mount / "vault_synthesizer").is_dir()
        assert (mount / "daily_driver").is_dir()
        assert (mount / "MEMORY_INDEX.md").is_file()
        # Idempotent: a second call must not raise and must not clobber.
        (mount / "shared" / "marker.md").write_text("existing")
        ensure_mount(mount, agent_ids=["vault_synthesizer", "daily_driver"])
        assert (mount / "shared" / "marker.md").read_text() == "existing"

    def test_manifest_has_well_known_header(self, tmp_path: Path):
        from lib.fleet_memory import ensure_mount
        mount = tmp_path / "fleet-memory"
        ensure_mount(mount, agent_ids=["vault_synthesizer"])
        manifest = (mount / "MEMORY_INDEX.md").read_text()
        assert manifest.startswith("# Fleet Memory Index")
        assert "_Auto-generated by lib.fleet_memory" in manifest


class TestFleetMemoryToolViewCreate:
    def test_constructor_requires_agent_id(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        with pytest.raises(TypeError):
            FleetMemoryTool(mount_root=tmp_fleet_memory)  # type: ignore[call-arg]

    def test_view_lists_agent_namespace(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        ns = tmp_fleet_memory / "vault_synthesizer"
        (ns / "lesson-1.md").write_text("first")
        (ns / "lesson-2.md").write_text("second")
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        result = tool._view_path("vault_synthesizer/")
        assert "lesson-1.md" in result
        assert "lesson-2.md" in result

    def test_view_reads_file_body(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        ns = tmp_fleet_memory / "vault_synthesizer"
        (ns / "lesson.md").write_text("# Lesson\nDon't trust mock retrievers.\n")
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        result = tool._view_path("vault_synthesizer/lesson.md")
        assert "Lesson" in result
        assert "Don't trust mock retrievers." in result

    def test_view_rejects_path_escape(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool, PathEscapeError
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        with pytest.raises(PathEscapeError):
            tool._view_path("../../../etc/passwd")

    def test_create_writes_to_agent_namespace(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path(
            "vault_synthesizer/pr52-stale-checkout.md",
            "PR #52 wrote pre-Tier-2 articles. Always filter to manifest.",
        )
        on_disk = tmp_fleet_memory / "vault_synthesizer/pr52-stale-checkout.md"
        assert on_disk.read_text().startswith("PR #52")

    def test_create_rejects_writes_outside_own_namespace(self, tmp_fleet_memory: Path):
        from lib.fleet_memory import FleetMemoryTool, NamespaceViolation
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        # Synth must not write into daily_driver/ directly.
        with pytest.raises(NamespaceViolation):
            tool._create_path("daily_driver/sneaky.md", "no")

    def test_create_allows_writes_to_shared(self, tmp_fleet_memory: Path):
        """Writes to shared/ are *allowed* by the namespace guard — the actual
        promotion ergonomics live in the explicit promote_to_shared() helper
        (Task 7). But the tool isn't blocked from writing directly to shared/
        because that's how an agent flushes an already-validated lesson."""
        from lib.fleet_memory import FleetMemoryTool
        tool = FleetMemoryTool(mount_root=tmp_fleet_memory, agent_id="vault_synthesizer")
        tool._create_path("shared/cross-fleet-lesson.md", "All agents read this.")
        assert (tmp_fleet_memory / "shared/cross-fleet-lesson.md").exists()
